#!/bin/sh
cd /usr/lib/unifi/

UNIFI_CORE_ENABLED=false
UNIFI_MONGODB_SERVICE_ENABLED=false
UNIFI_JVM_OPTS='-Xmx1024M -XX:+UseParallelGC'

source /usr/lib/unifi/data/system_env
source /etc/default/unifi

/usr/sbin/unifi-network-service-helper init
/usr/sbin/unifi-network-service-helper init-uos

/usr/bin/java \
    -Dfile.encoding=UTF-8 \
    -Djava.awt.headless=true \
    -Dapple.awt.UIElement=true \
    -Dunifi.core.enabled=${UNIFI_CORE_ENABLED} \
    -Dunifi.mongodb.service.enabled=${UNIFI_MONGODB_SERVICE_ENABLED} \
    $UNIFI_JVM_OPTS \
    -XX:+ExitOnOutOfMemoryError \
    -XX:+CrashOnOutOfMemoryError \
    -XX:ErrorFile=/usr/lib/unifi/logs/unifi_crash.log \
    -Xlog:gc:logs/gc.log:time:filecount=2,filesize=5M \
    --add-opens java.base/java.lang=ALL-UNNAMED \
    --add-opens java.base/java.time=ALL-UNNAMED \
    --add-opens java.base/sun.security.util=ALL-UNNAMED \
    --add-opens java.base/java.io=ALL-UNNAMED \
    --add-opens java.rmi/sun.rmi.transport=ALL-UNNAMED \
    -jar /usr/lib/unifi/lib/ace.jar start

/usr/sbin/unifi-network-service-helper cleanup